### ISSUE TITLE
Two Teensy 3.2 don't talk to each other

### ISSUE THREAD

**Issue by fricklr** [chrisstaite/TeensyDmx#8]
Hi,
I just tested your library on two Teensy 3.2 with Teensyduino 1.35. but sadly they can't talk to each other - the sender code from your example on it's own works, I tested it with a dimmer. 
Do you have any ideas?
Thank you very much

**Comment by peternewman** [comment]
I think I decided the receive code is broken while trying to make an RDM Controller, I think I've sorted that bit (the RDM controller stuff still needs a fair bit more work). I'll see if I can pull that fix out as a patch and open a PR for it.

**Comment by chrisstaite** [comment]
I've been meaning to look into this, but I've been very busy on other projects recently. Very happy to take pull requests.

**Comment by peternewman** [comment]
Try this @fricklr , while @chrisstaite and I refine the PR if necessary before it gets merged https://github.com/chrisstaite/TeensyDmx/pull/12

**Comment by peternewman** [comment]
Fixed via #14 @chrisstaite .

**Comment by peternewman** [comment]
Care to close this one then @chrisstaite ?

**Comment by chrisstaite** [comment]
If we could get someone else to test the new code, that would be good... @fricklr, are you able to test?

**Comment by peternewman** [comment]
Fair point, admittedly I'd not actually tested a pair talking together...

**Comment by fricklr** [comment]
Sorry, I'm without my gear for the next weeks. But it's  great news that it should work now. Thanks a bunch! 
Cheers

-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 28.09.2017, 11:05 AM, Chris <notifications@github.com> schrieb:
If we could get someone else to test the new code, that would be good... @fricklr, are you able to test?
